#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh &

# key bindings
sxhkd &

# Set some bsp specific stuff
bspc monitor -d x x x x x x x
bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config click_to_focus true

bspc config focus_follows_pointer false

bspc config normal_border_color	"#131520"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#ffb52a"
bspc config presel_feedback_color	"#ffb52a"
bspc config urgent_border_color "#bd2c40"

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 7

###---Rules---###
bspc rule -a Zathura state=tiled
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
